language: c

os:
 - linux
 - osx

env:
 - EXTRALIBS=""
 - EXTRALIBS="libaa1-dev"
 - EXTRALIBS="libcdk5-dev"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install autopoint libgphoto2-dev $EXTRALIBS

compiler:
 - gcc
 - clang

script:
 - mkdir lg2 ; cd lg2 ; git clone git@github.com:gphoto/libgphoto2.git ; cd libgphoto2 ; autoreconf -i -f ; ./configure --prefix=/usr --libdir=/usr/lib && make && sudo make install ; cd ../../
 - autoreconf -i -f
 - ./configure && make && make check

notifications:
  recipient:
   - marcus@jet.franken.de
  email:
    on_success: change
    on_failure: always
