language: c

os:
 - linux
 - osx

env:
 - EXTRALIBS="libusb-1.0-0-dev libgd2-xpm-dev"
 - EXTRALIBS="libusb-1.0-0-dev libgd2-xpm-dev libaa1-dev"
 - EXTRALIBS="libusb-1.0-0-dev libgd2-xpm-dev libaa1-dev libcdk5-dev"

before_install:
 - sudo apt-get update -qq || brew update
 - sudo apt-get install autopoint $EXTRALIBS || brew install gettext

compiler:
 - gcc
 - clang

script:
 - mkdir lg2 ; cd lg2 ; git clone git@github.com:gphoto/libgphoto2.git ; cd libgphoto2 ; autoreconf -i -f ; ./configure --prefix=/usr --libdir=/usr/lib && make && sudo make install ; cd ../../
 - autoreconf -i -f
 - ./configure && make && make check

notifications:
  recipient:
   - marcus@jet.franken.de
  email:
    on_success: change
    on_failure: always
